// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnGmiUSLPsSM_F_1TSGXa0f7SMGWf9j4',
    appId: '1:812341267523:web:f65972932820b1cf2858f6',
    messagingSenderId: '812341267523',
    projectId: 'app-connectly',
    authDomain: 'app-connectly.firebaseapp.com',
    storageBucket: 'app-connectly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZucGvxBwSIubqbihQhj4QfIqrsqn3kVk',
    appId: '1:812341267523:android:f7fe2378d4d3e37d2858f6',
    messagingSenderId: '812341267523',
    projectId: 'app-connectly',
    storageBucket: 'app-connectly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA--9eMD7vOJTqiug6xzwiyR4sXxFXl3Q',
    appId: '1:812341267523:ios:268a5429187617c32858f6',
    messagingSenderId: '812341267523',
    projectId: 'app-connectly',
    storageBucket: 'app-connectly.appspot.com',
    iosBundleId: 'com.example.connectly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA--9eMD7vOJTqiug6xzwiyR4sXxFXl3Q',
    appId: '1:812341267523:ios:268a5429187617c32858f6',
    messagingSenderId: '812341267523',
    projectId: 'app-connectly',
    storageBucket: 'app-connectly.appspot.com',
    iosBundleId: 'com.example.connectly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnnGmiUSLPsSM_F_1TSGXa0f7SMGWf9j4',
    appId: '1:812341267523:web:2775c850602c65482858f6',
    messagingSenderId: '812341267523',
    projectId: 'app-connectly',
    authDomain: 'app-connectly.firebaseapp.com',
    storageBucket: 'app-connectly.appspot.com',
  );

}